services:
  - type: web
    name: ai-knowledge-sprint-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: WEAVIATE_URL
        sync: false
      - key: FRIENDLI_API_KEY
        sync: false
      - key: COMET_API_KEY
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
    healthCheckPath: /
